CRUD/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('persona.urls')),  # Asegúrate de que esto esté correcto
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

persona/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.lista_usuarios, name='lista_usuarios'),
    path('nuevo/', views.crear_usuario, name='crear_usuario'),
    path('editar/<int:pk>/', views.editar_usuario, name='editar_usuario'),
    path('eliminar/<int:pk>/', views.eliminar_usuario, name='eliminar_usuario'),
]

persona/models.py
from django.db import models
from datetime import date
from PIL import Image

class Usuario(models.Model):
    foto_perfil = models.ImageField(upload_to='fotos_perfiles/')
    nombre_apellido = models.CharField(max_length=100)
    correo_electronico = models.EmailField()
    telefono = models.CharField(max_length=20)
    fecha_nacimiento = models.DateField()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.foto_perfil.path)
        output_size = (100, 100)  # Tamaño deseado
        img.thumbnail(output_size)
        img.save(self.foto_perfil.path)

    def calcular_edad(self):
        hoy = date.today()
        return hoy.year - self.fecha_nacimiento.year - ((hoy.month, hoy.day) < (self.fecha_nacimiento.month, self.fecha_nacimiento.day))
    
    def __str__(self):
        return self.nombre_apellido

persona/forms.py
from django import forms
from .models import Usuario

class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['foto_perfil', 'nombre_apellido', 'correo_electronico', 'telefono', 'fecha_nacimiento']
        widgets = {
            'fecha_nacimiento': forms.DateInput(attrs={'type': 'date'}),
        }

persona/views.py
from django.shortcuts import render, redirect
from .models import Usuario
from .forms import UsuarioForm

def lista_usuarios(request):
    usuarios = Usuario.objects.all()
    return render(request, 'usuarios/lista.html', {'usuarios': usuarios})

def crear_usuario(request):
    if request.method == "POST":
        form = UsuarioForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('lista_usuarios')
    else:
        form = UsuarioForm()
    return render(request, 'usuarios/form.html', {'form': form})

def editar_usuario(request, pk):
    usuario = Usuario.objects.get(id=pk)
    if request.method == "POST":
        form = UsuarioForm(request.POST, request.FILES, instance=usuario)
        if form.is_valid():
            form.save()
            return redirect('lista_usuarios')
    else:
        form = UsuarioForm(instance=usuario)
    return render(request, 'usuarios/form.html', {'form': form})

def eliminar_usuario(request, pk):
    Usuario.objects.get(id=pk).delete()
    return redirect('lista_usuarios')

persona/templates/usuarios/form.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario de Usuario</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container form-container">
        <h1>Formulario de Usuario</h1>
        <form method="post" enctype="multipart/form-data" class="usuario-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_foto_perfil">Foto perfil:</label>
                {{ form.foto_perfil }}
            </div>
            <div class="form-group">
                <label for="id_nombre_apellido">Nombre y apellido:</label>
                {{ form.nombre_apellido }}
            </div>
            <div class="form-group">
                <label for="id_correo_electronico">Correo electrónico:</label>
                {{ form.correo_electronico }}
            </div>
            <div class="form-group">
                <label for="id_telefono">Teléfono:</label>
                {{ form.telefono }}
            </div>
            <div class="form-group">
                <label for="id_fecha_nacimiento">Fecha de nacimiento:</label>
                {{ form.fecha_nacimiento}}
            </div>
            <button type="submit" class="btn">Guardar</button>
            <a href="{% url 'lista_usuarios' %}" class="btn">Volver a la lista</a>
        </form>
    </div>
</body>
</html>

persona/templates/usuarios/lista.html
{% load static %}

<!DOCTYPE html>

<html>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Usuarios</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
<body>
    <div class="container">
        <h1>Lista de Usuarios</h1>
        <!-- Botón de Crear Nuevo Usuario en la esquina superior derecha -->
        <a href="{% url 'crear_usuario' %}" class="btn btn-crear top-right">Crear Nuevo Usuario</a>

        <!-- Grid para mostrar los usuarios -->
        <div class="grid-container">
            {% for usuario in usuarios %}
                <div class="usuario-card">
                    <!-- Suponiendo que el modelo tiene un campo 'foto_perfil' -->
                    <img src="{{ usuario.foto_perfil.url }}" class="usuario-foto" alt="Foto de perfil">
                    <div class="usuario-info">
                        <h3>{{ usuario.nombre_apellido }}, {{ usuario.calcular_edad }}</h3>
                        <p>{{ usuario.telefono }}</p>
                        <p>{{ usuario.correo_electronico }}</p>
                    </div>
                    <!-- Agrega más detalles del usuario si lo deseas -->
                    <a href="{% url 'editar_usuario' usuario.id %}" class="btn">Editar</a>
                    <a href="{% url 'eliminar_usuario' usuario.id %}" class="btn">Eliminar</a>
                </div>
            {% empty %}
                <p>No hay usuarios registrados.</p>
            {% endfor %}
        </div>
    </div>
</body>
</html>